spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec_201910a
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: federer.tennis.nadal.1023@gmail.com
    password: agdavrmtwctyrokl
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    
    
    